
                                        <div class="page-title title-buttons">
    <button id="requestnew" class="button f-left"><span><span id="requestrmaspan" >Request a new return</span></span></button>
    <button id="findrma" class="button f-left"><span><span id="findrmaspan" >Check status of an existing return</span></span></button>
    
</div>
<div id="messages">
    </div>
    <div id="container-requestrma">
    <form id="awrma-new-form" method="post" action="<?php echo $this->getchkorderActionUrl() ?>">
    <div class="fieldset">
        <h2 class="legend">Order Information<!--<a href="<?php echo $this->getUrl('multisuppliers/rma/search') ?>" class="f-right link-awrma-newrma">Search A RMA</a>--></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label class="required" for="awrma-orderid"><em>*</em>Order Id</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" id="awrma-orderid" name="orderid">
                    </div>
                </div>
                <div class="field">
                    <label class="required" for="awrma-email"><em>*</em>E-mail</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" id="awrma-email" name="email">
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <button id="awrma-new-submit" class="button" title="Submit Request" type="submit"><span><span>Submit Request</span></span></button>
    </div>
</form>
    </div>
<div id="container-findrma"><form id="awrma-find-form" method="post" action="<?php echo $this->getUrl('multisuppliers/rma/chkrma') ?>">
    <div class="fieldset">
        <h2 class="legend">RMA Information</h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label class="required" for="awrma-orderid"><em>*</em>RMA Id</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" id="awrma-orderid" name="rmaid">
                    </div>
                </div>
                <div class="field">
                    <label class="required" for="awrma-email"><em>*</em>E-mail</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" id="awrma-email" name="email">
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <button id="awrma-new-submit" class="button" title="Submit Request" type="submit"><span><span>Submit Request</span></span></button>
    </div>
</form></div>
<style>
.rmastyle{
    background-color:#D03071 !important;
    color: #ffffff !important;
}</style>
<script type="text/javascript">
    var awrmaNewForm = new VarienForm('awrma-new-form');
    var awrmafindform = new VarienForm('awrma-find-form');
    $("container-findrma").hide();
    $("container-requestrma").hide();
    $("requestnew").observe("click",function(){
        $('findrmaspan').removeClassName('rmastyle');
        $('requestrmaspan').addClassName('rmastyle');
        

$("container-findrma").hide();
        $("container-requestrma").show();
});

$("findrma").observe("click",function(){
   $('requestrmaspan').removeClassName('rmastyle');
 $('findrmaspan').addClassName('rmastyle');   
$("container-requestrma").hide();
$("container-findrma").show();
        
});
</script>                