

<script type='text/javascript'>
var ps = jQuery.noConflict();
ps(document).ready(function() {
    ps.ajax({

  type: "GET",

  url: ps("#baseurl").val() + "multisuppliersmarketplace/brand/getcategorycats?catid="+ps("#maincategorycat<?php echo  $this->getCategoryFor(); ?>").val() ,
})

  .done(function( msg ) {        
ps("#ajax_id_<?php echo  $this->getCategoryFor(); ?>").text(' ');
ps("#ajax_id_<?php echo  $this->getCategoryFor(); ?>").append(msg);
  });
  });    
 </script>
<input  id="baseurl" type="hidden" value="<?php echo Mage::getBaseUrl(); ?>"/>
<input id="maincategorycat<?php echo  $this->getCategoryFor(); ?>" type="hidden" value="<?php echo  $this->getCategoryFor(); ?>" />  
<?php
 ?>
<div id="ajax_id_<?php echo  $this->getCategoryFor(); ?>">
</div>

<style>
.cat-img{
    margin-bottom: 0;
    margin-right: -10px;
    margin-top: -10px;
    background-color: #e3deda;}
</style>