<?php
if(Mage::getStoreConfig('multisuppliers/multisuppliers/location_enable', Mage::app()->getStore()) == 0):
 if(Mage::getModel('core/cookie')->get('Country') == ''):
       $remoteAddr = Mage::helper('core/http')->getRemoteAddr(true);
        $ip = long2ip($remoteAddr);
       $info = json_decode(file_get_contents("http://ipinfo.io/{$ip}"));

Mage::getModel('core/cookie')->set('testcookie', 'testvalue');      

    if (Mage::getModel('core/cookie')->get('testcookie') != "") 

       {
        if(Mage::getModel('core/cookie')->get('Country') == '')

       {

        if($info->country != "CA" || $info->country != "US")
            {
               $ipcountry = "CA"; 
            }else{
               $ipcountry = $info->country; 
            }
        if($info->region != ""):
        $ipregion = $info->region;
        else:
        $ipregion = "All";        
        endif;        
        $ipcity = "All";

        

       }else{

        $ipcountry = Mage::getModel('core/cookie')->get('Country');

        $ipregion = Mage::getModel('core/cookie')->get('Region');

        $ipcity = "All";

       }
       }else{
        if(Mage::getSingleton('core/session', array('name' => 'frontend'))->getCountry() == '')

       {

        if($info->country != "CA" || $info->country != "US")
            {
               $ipcountry = "CA"; 
            }else{
               $ipcountry = $info->country; 
            }

       if($info->region != ""):
        $ipregion = $info->region;
        else:
        $ipregion = "All";
        endif;

        $ipcity = "All";

        

       }else{

        $ipcountry = Mage::getSingleton('core/session', array('name' => 'frontend'))->getCountry();

        $ipregion = Mage::getSingleton('core/session', array('name' => 'frontend'))->getRegion();

        $ipcity = "All";

       }
       }


include_once(Mage::getBaseDir().'/var/geoip/geoip.inc');
        // Open Geo IP binary data file
        $geoIp = geoip_open(Mage::getBaseDir().'/var/geoip/GeoIP.dat',GEOIP_STANDARD);
        
        $currencyCode = geoip_currency_code_by_country_code($geoIp,$ipcountry);
        
        if($currencyCode !="")
        Mage::app()->getStore()->setCurrentCurrencyCode($currencyCode);
       
       Mage::getModel('core/cookie')->set('testcookie', 'testvalue');//setcookie('testcookie', "testvalue");       

        if($ipcountry == "")
        {
           $ipcountry = "CA"; 
        }

    if (Mage::getModel('core/cookie')->get('testcookie') != "") {
        Mage::getModel('core/cookie')->set('Country', $ipcountry);
        Mage::getModel('core/cookie')->set('Region', $ipregion);
        Mage::getModel('core/cookie')->set('City', $ipcity);
        Mage::getModel('core/cookie')->set('Psolflag', "true");
    } else {
        Mage::getSingleton('core/session')->setCountry($ipcountry);
        Mage::getSingleton('core/session')->setRegion($ipregion);
         Mage::getSingleton('core/session')->setCity($ipcity);
         Mage::getSingleton('core/session')->setPsolflag("true");
    }

    ?>
<script>
//location.reload();
</script>
<?php    
    endif;
    
    endif;            
  ?>
















<?php 
$piecesurl = explode("/" , $_SERVER['REQUEST_URI']);
if(in_array("vendorregisteration",$piecesurl))
{}else{?>
<!--<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>-->
<?php }
?>


<?php  

 Mage::getModel('core/cookie')->set('testcookie', 'testvalue');      

    if (Mage::getModel('core/cookie')->get('testcookie') != "") {
        $flags = Mage::getModel('core/cookie')->get('Psolflag');
    } else {
       $flags = Mage::getSingleton('core/session', array('name' => 'frontend'))->getPsolflag();
    }

if($flags == '')

{?>

<script type='text/javascript'>

var ps = jQuery.noConflict();

ps(document).ready(function() {  
    ps(".location-country").click(function() {
    ps("#country_id_ajax").val(ps(this).attr('rel'));
        ps('.close').click();
    
});


overlay.appendTo(document.body);
ps(".psol_content").show();
ps(".popup").show();

ps("#emsg").hide();

ps(function(){

var overlay = ps('<div id="overlay"></div>');





ps('.location span').click(function(){

    ps('#emsg').show();

    overlay.show();

overlay.appendTo(document.body);
ps(".psol_content").show();
ps(".popup").show();

})

ps('#test').click(function(){

    ps('#emsg').show();

    overlay.show();

overlay.appendTo(document.body);
ps(".psol_content").show();
ps(".popup").show();

})

ps('.close').click(function(){ 
    ps.ajax({

  type: "GET",

  url: ps("#baseurl").val() + "multisuppliersmarketplace/brand/savecookie?categoryname="+ps(this).find('span').find('span').attr("rel") ,
})

  .done(function( msg ) {
  });

    var state = "";

    if(ps(".ajaxstateselectpopup").is(':visible'))

       {
       

        state = ps(".ajaxstateselectpopup").children("option").filter(":selected").text();
       }

       else{

        state = ps(".ajaxstateselectpopuptext").val();
       }

    if(ps("#country_id_ajax").val() != "" && state != "" && ps("#city_ship_ajax").val() != "")

    {

        ps.ajax({

  type: "GET",

  url: ps("#baseurl").val() + "multisuppliersmarketplace/index/test",

  data: { country:ps("#country_id_ajax").val() , region:  state ,city: ps("#city_ship_ajax").val(),flag:"true" }

})

  .done(function( msg ) {

    ps("#overlay").hide();
        location.reload();
ps("#overlay").remove();

  



  });

   ps('.popup').hide();

    }

    else{

        alert('Please verify Location');

    } 

    



return false;

});

});

});

</script>

<?php }else{

    

    ?>

    <script type='text/javascript'>

var ps = jQuery.noConflict();

ps(document).ready(function() {
    ps(".location-country").click(function() {
    ps("#country_id_ajax").val(ps(this).attr('rel'));
        ps('.close').click();
    
});
ps('#overlay').live('click',function(){
     ps(".popup").hide();
     ps("#overlay").hide();

ps("#overlay").remove();
}); 
    ps(".popup").hide();

    ps('#emsg').hide();

ps(function(){

ps('#test').click(function(){

    

    var overlay = ps('<div id="overlay"></div>');

    overlay.show();

overlay.appendTo(document.body);
ps(".psol_content").show();
ps(".popup").show();

ps('#emsg').show();

});

ps('.close').click(function(){
 ps.ajax({

  type: "GET",

  url: ps("#baseurl").val() + "multisuppliersmarketplace/brand/savecookie?categoryname="+ps(this).find('span').find('span').attr("rel") ,
})

  .done(function( msg ) {
  });
    var state = "";

    if(ps(".ajaxstateselectpopup").is(':visible'))

       {

        state = ps(".ajaxstateselectpopup").children("option").filter(":selected").text()

       }

       else{

        state = ps(".ajaxstateselectpopuptext").val();

       }

    if(ps("#country_id_ajax").val() != "" && state != "" && ps("#city_ship_ajax").val() != "")

    {

        ps.ajax({

  type: "GET",

  url: ps("#baseurl").val() + "multisuppliersmarketplace/index/test",

  data: { country:ps("#country_id_ajax").val() , region:  state ,city: ps("#city_ship_ajax").val(),flag:"true" }

})

  .done(function( msg ) {
if(msg == "alldone")
{
    
    var full_url = document.URL.replace("?chkcart=ttrue","");
    var loc = window.location += "?chkcart=ttrue";
    window.location.href = full_url + "?chkcart=ttrue";
    //location.reload();
}
    ps("#overlay").hide();

ps("#overlay").remove();

  



  });

   ps('.popup').hide();

    }

    else{

        alert('Please verify Location');

    } 

    



return false;

});

});

});

</script>

<?php  }



?>

</head>




<a style="display: none;" id="test"></a>



<?php

       function ip_details($ip){

        $json = file_get_contents("http://ipinfo.io/{$ip}");

        $jsonDecode = json_decode($json);

        return $jsonDecode;

       }

       $remoteAddr = Mage::helper('core/http')->getRemoteAddr(true);

       $info = ip_details(long2ip($remoteAddr));

Mage::getModel('core/cookie')->set('testcookie', 'testvalue');      

    if (Mage::getModel('core/cookie')->get('testcookie') != "") 

       {
        if(Mage::getModel('core/cookie')->get('Country') == '')

       {

            if($info->country != "CA" || $info->country != "US")
            {
               $ipcountry = "CA"; 
            }else{
               $ipcountry = $info->country; 
            }
        

        $ipregion = $info->region;

        $ipcity = $info->city;

        

       }else{

        $ipcountry = Mage::getModel('core/cookie')->get('Country');

        $ipregion = Mage::getModel('core/cookie')->get('Region');

        $ipcity = Mage::getModel('core/cookie')->get('City');

       }
       }else{
        if(Mage::getSingleton('core/session', array('name' => 'frontend'))->getCountry() == '')

       {

        if($info->country != "CA" || $info->country != "US")
            {
               $ipcountry = "CA"; 
            }else{
               $ipcountry = $info->country; 
            }

        $ipregion = $info->region;

        $ipcity = $info->city;

        

       }else{

        $ipcountry = Mage::getSingleton('core/session', array('name' => 'frontend'))->getCountry();

        $ipregion = Mage::getSingleton('core/session', array('name' => 'frontend'))->getRegion();

        $ipcity = Mage::getSingleton('core/session', array('name' => 'frontend'))->getCity();

       }
       }
       

       ?>
<div style="
    right: 0px;
    top: 30px;
    width: 421px;
    z-index: 999999; position: absolute; background: #ffffff; padding: 5px 10px; display: none; border: 3px solid #3ba2db;" id="location-flex-popup">

<ul style="" class="form-list">

            <li style="margin-bottom: 0px;" class="fields">

                    <div style="width: 31.3% !important; margin-right: 10px; margin-bottom: 0px;"  style="" class="field">


                        
                        <input type="hidden" id="country_id_ajax" value="<?php echo $ipcountry ?>" />
                        <input type="hidden" id="regiontext" value="<?php echo "All" ?>" />
                        <input type="hidden" id="region_id_ajax" value="<?php echo "All" ?>" />
                        <input type="hidden" id="city_ship_ajax" value="<?php echo "All" ?>" />
                        <div class="input-box" style="width: 100% !important;">
                        <span rel="<?php echo "CA"; ?>" <?php if($ipcountry == "CA"){echo 'style="cursor: none; font-weight: bold;"';}else{echo 'style="display: block; line-height: 10px;cursor: pointer;"';}?>  class="<?php if($ipcountry != "CA"){echo 'location-country';} ?>"><?php echo "CANADA"; ?></span>
                        <span rel="<?php echo "US"; ?>" <?php if($ipcountry == "US"){echo 'style="cursor: none; font-weight: bold;"';}else{echo 'style="display: block; line-height: 25px;cursor: pointer;"';}?> class="<?php if($ipcountry != "US"){echo 'location-country';} ?>"><?php echo "USA"; ?></span>
                        </div>
                    </div>

                    <!--<div class="field" style=" display: none !important;width: 31.3% !important; margin-right: 10px; margin-bottom: 0px;">

                        <label for="region_id_ajax"><?php echo $this->__('State/Province') ?></label>

                        <div class="input-box" style="width: 100% !important;">
                        <?php if($this->getRegionCollection($ipcountry,$ipregion) == "none"){
                            ?>
                            <select  style="background: #e3deda; color: #000000; display: none; width: 100% !important;" id="region_id_ajax" title="<?php echo $this->__('State/Province') ?>" class="ajaxstateselectpopup">

                                <option>Please Enter Province</option>

                            </select>
                            <input style="width: 100% !important; background: #e3deda; color: #000000;" type="text" id="regiontext"  value="<?php echo $ipregion;?>" title="<?php echo $this->__('State/Province') ?>" class="ajaxstateselectpopuptext input-text" />
                            <?php
                        }else{
                            ?>
                            <select style="width: 100% !important;background: #e3deda; color: #000000;" id="region_id_ajax" title="<?php echo $this->__('State/Province') ?>" class="ajaxstateselectpopup">

                                <?php echo $this->getRegionCollection($ipcountry,$ipregion); ?>

                            </select>
                            <input type="text" id="regiontext"  value="<?php echo $ipregion;?>" title="<?php echo $this->__('State/Province') ?>" class="ajaxstateselectpopuptext input-text" style="display: none; width: 100% !important; background: #e3deda; color: #000000;" />
                        <?php } ?>                        

                            

                            

                        </div>

                    </div>

                    <div style="display: none !important; width: 31.3% !important; margin-right: 10px;  margin-bottom: 0px; " class="field">

                        <label for="city_ship_chk"><?php echo $this->__('Add City') ?></label>

                        <div style="width: 100% !important;" class="input-box">

                            <input style="width: 100% !important; background: #e3deda; color: #000000;" type="text" title="<?php echo $this->__('City_ship') ?>" class=" ajaxcitytext input-text " id="city_ship_ajax" value="<?php echo $ipcity;?>"/>

                        </div>

                    </div>-->

                    <input  id="baseurl" type="hidden" value="<?php echo Mage::getBaseUrl(); ?>"/>

                    </li>

                    </ul>
                    <button style="display: none !important;" class="button close"><span><span style="background: gray; color: black !important; font-weight: bold;">Submit</span></span></button>

                    </div>
       
